swagger: "2.0"
info:
  title: Meeting scheduler
  version: 1.0.0
basePath: /
paths:
  /api/v1/schedule-meeting:
    post:
      summary: Schedule a meeting
      tags:
        - Meetings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                date:
                  description: Meeting date in YYYY-MM-DD format
                  type: string
                  format: date
                start_time:
                  in: body
                  description: Meeting start time
                  type: string
                  pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$"
                end_time:
                  in: body
                  description: Meeting end time
                  type: string
                  pattern: "^([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$"
                room_id:
                  in: body
                  description: Meeting room ID
                  type: string
                  enum:
                    - R1
                    - R2
                    - R3
                    - R4
                    - R5
                attendees:
                  in: body
                  description: Meeting attendees
                  type: string
                  example: 'P1,P2'
              required:
                  - date
                  - start_time
                  - end_time
                  - room_id
                  - attendees
      responses:
        "200":
          description: Meeting scheduled successfully
        "400":
          description: The room is not available during the specified time slot.
        "403":
          description: "The following attendees are not available during the specified time slot: P1, P2"
        "500":
          description: Internal server error
